name: Vertretungsplan

on:
  schedule:
    - cron: "0 16,18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  send-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/
