name: Vertretungsplan

on:
  schedule:
    - cron: "0 16,18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  send-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt

      - name: Script ausführen
        run: python main.py
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}

      - name: Änderungen committen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add *.pdf

          if ! git diff --staged --quiet; then
            git commit -m "Update Vertretungsplan"
            git push
          fi
